openapi: 3.0.3
externalDocs:
  description: 'Edu System site'
  url: 'https://edu-docker.herokuapp.com/'
info:
  title: Edu System REST API
  description: Edu System
  version: 1.0.0-SNAPSHOT
  contact:
    name: 孟德维
    email: mengdewei@gmail.com
servers:
  - url: 'https://edu-docker.herokuapp.com'
    description: 生产环境
tags:
  - name: edu-api
    description: 登录及认证相关接口
  - name: teacher
    description: 老师相关接口
  - name: student
    description: 学生相关接口


security:
  - KeyAuth: []
paths:
  '/api/auth/login':
    post:
      tags:
        - edu-api
      summary: 登录接口
      operationId: login
      requestBody:
        description: 用户信息
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/UserRegInfo'
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserInfo'

  '/api/auth/reg':
    post:
      tags:
        - edu-api
      summary: 注册接口
      operationId: register
      requestBody:
        description: 用户信息
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/UserRegInfo'
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserInfo'

  '/api/auth/line/login':
    post:
      tags:
        - edu-api
      summary: 使用 line id token 登陆指定用户
      operationId: lineLogin
      requestBody:
        description: 绑定信息
        required: true
        content:
          'application/json':
            schema:
              properties:
                token:
                  type: string
                  description: Line ID Token (jwt)
                userId:
                  type: integer
                  format: int32
                  description: User ID
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserInfo'


  '/api/auth/line/users':
    post:
      tags:
        - edu-api
      summary: 使用 line id token 查询所有绑定的用户
      operationId: users
      requestBody:
        description: 绑定信息
        required: true
        content:
          'application/json':
            schema:
              properties:
                token:
                  type: string
                  description: Line ID Token (jwt)
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                type: array
                description: 结果
                items:
                  $ref: '#/components/schemas/UserInfo'
  '/api/line/bind':
    post:
      tags:
        - edu-api
      summary: 绑定 Line 账号
      operationId: bind
      requestBody:
        description: 绑定信息
        required: true
        content:
          'application/json':
            schema:
              properties:
                token:
                  type: string
                  description: Line ID Token (jwt)
      responses:
        '200':
          description: 成功

  '/api/line/unbind':
    put:
      tags:
        - edu-api
      summary: 解绑 Line 账号
      operationId: unbind
      responses:
        '200':
          description: 成功

  '/api/schools':
    post:
      tags:
        - teacher
      summary: 创建学校
      operationId: createSchools
      requestBody:
        description: 绑定信息
        required: true
        content:
          'application/json':
            schema:
              properties:
                name:
                  type: string
                  description: 学校名字
      responses:
        '200':
          description: 成功
    get:
      tags:
        - teacher
      summary: 老师所属学校的列表
      operationId: schools
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                type: array
                description: 结果
                items:
                  $ref: '#/components/schemas/SchoolInfo'


  '/api/schools/{schoolId}/students':
    post:
      tags:
        - teacher
      summary: 老师创建学生账号
      operationId: createStudents
      parameters:
        - name: schoolId
          in: path
          required: true
          description: 学校ID
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/*:
            schema:
              $ref: '#/components/schemas/UserRegInfo'
      responses:
        '200':
          description: 成功


  '/api/schools/students':
    get:
      tags:
        - teacher
      summary: 老师的学生（老师所属多个学校）
      operationId: Students
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                type: array
                description: 结果
                items:
                  $ref: '#/components/schemas/StudentInfo'


  '/api/schools/{schoolId}/invites':
    post:
      tags:
        - teacher
      summary: 学校管理员邀请创建老师账号
      operationId: invites
      parameters:
        - name: schoolId
          in: path
          required: true
          description: 学校ID
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/*:
            schema:
              $ref: '#/components/schemas/UserRegInfo'
      responses:
        '200':
          description: 成功

  '/api/teachers/students/subscribe':
    get:
      tags:
        - teacher
      summary: 查看关注自己的学生
      operationId: subscribe
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                type: array
                description: 结果
                items:
                  $ref: '#/components/schemas/StudentInfo'

  '/api/talk/teacher/{studentId}':
    post:
      tags:
        - teacher
      summary: 老师给学生发message
      operationId: teacherTalk
      parameters:
        - name: studentId
          in: path
          required: true
          description: 学生id
          schema:
            type: integer
            format: int64
      requestBody:
        description: 绑定信息
        required: true
        content:
          'application/json':
            schema:
              properties:
                content:
                  type: string
                  description: 内容
      responses:
        '200':
          description: 成功

  '/api/talk/student/{teacherId}':
    post:
      tags:
        - student
      summary: 学生给老师发message
      operationId: studentTalk
      parameters:
        - name: teacherId
          in: path
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
      requestBody:
        description: 绑定信息
        required: true
        content:
          'application/json':
            schema:
              properties:
                content:
                  type: string
                  description: 内容
      responses:
        '200':
          description: 成功


  '/api/students/school':
    get:
      tags:
        - student
      summary: 该学生所在学校的信息
      operationId: schoolInfo
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/SchoolInfo'

  '/api/students/teachers':
    get:
      tags:
        - student
      summary: 学生所在学校的老师们
      operationId: teachers
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/StudentTeacherInfo'


  '/api/students/subscribes':
    get:
      tags:
        - student
      summary: 学生关注的老师门
      operationId: subscribes
      responses:
        '200':
          description: 成功
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/StudentTeacherInfo'

  '/api/students/subscribes/{teacherId}':
    post:
      tags:
        - student
      summary:  关注老师请求接口
      operationId: subscribes
      parameters:
        - name: teacherId
          in: path
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功


  '/api/students/unsubscribes/{teacherId}':
    post:
      tags:
        - student
      summary:  取消关注老师请求接口
      operationId: deleteSubscribe
      parameters:
        - name: teacherId
          in: path
          required: true
          description: 老师id
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功

components:
  # security definition
  securitySchemes:
    KeyAuth:
      type: apiKey
      in: header
      name: 'Authorization'
  # parameters definition
  schemas:
    StudentTeacherInfo:
      type: object
      description: 关注老师Vo
      properties:
        id:
          type: integer
          description: 老师id
        name:
          type: string
          description: 老师姓名
        following:
          type: string
          description: 是否关注

    StudentInfo:
      type: object
      description: 学生的Vo
      properties:
        id:
          type: integer
          description: 学生id
        name:
          type: string
          description: 学生姓名
        school_name:
          type: string
          description: 学校名称

    SchoolInfo:
      type: object
      description: 用户信息的Vo
      properties:
        id:
          type: integer
          description: 学校id
        name:
          type: string
          description: 学校名称
        approve_at:
          type: string
          description: 审批日期
        created_at:
          type: string
          description: 创建日期
        is_manager:
          type: string
          description: 当前user是否为管理员


    UserInfo:
      type: object
      description: 用户信息的Vo
      properties:
        id:
          type: integer
          description: 用户id
        name:
          type: string
          description: 姓名
        access_token:
          type: string
          description: access_token
        expires_at:
          type: string
          description: 过期时间
        lineBinded:
          type: boolean
          description: 是否绑定Line
        role:
          type: string
          description: 角色
    UserRegInfo:
      type: object
      description: 用户注册的Vo
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          description: 姓名
        email:
          type: string
          description: 邮箱
        password:
          type: string
          description: 密码
